server:
  port: 8443  #注意，这里是https访问的的端口号
  ssl:
<<<<<<< HEAD
    key-store:
    key-store-password:
=======
    key-store: file:C:\Users\steve\OneDrive\LabData\计算机学院\研一上学期\人机交互\Eshop-SpringBoot\src\main\resources\client.p12
    key-store-password: 12345678
>>>>>>> 49f154ab2a60496bdee6289f94cfb7a711c9fbb5
    key-store-type: PKCS12
    key-alias: client

# mysql
spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost:3306/hci?userSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # mysql8:  url: url: jdbc:mysql//localhost:3306/mybatis_plus?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 设置开发环境
  profiles:
    active: dev


mybatis-plus:
  # 配置日志 (系统自带的，控制台输出)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
